# Generated by Django 4.0.4 on 2022-05-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
